### PR TITLE
Support for multi-scene files

### LINKED ISSUE #1: Can't open more than one region
Hey @jwindhager ,

we now encountered the issues that when trying to open a czi file containing  more than one imaged region it fails with:

```
/Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari/__main__.py:305: UserWarning: pythonw executable not found.
To unfreeze the menubar on macOS, click away from napari to another app, then reactivate napari. To avoid this problem, please install python.app in conda using:
conda install -c conda-forge python.app
  warnings.warn(msg)
2021-02-24 14:44:46.957 python[64501:5438075] -[NSNull length]: unrecognized selector sent to instance 0x7fff8861bc00
2021-02-24 14:44:46.957 python[64501:5438075] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7fa4e144c820> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff8861bc00
2021-02-24 14:44:46.957 python[64501:5438075] -[NSNull length]: unrecognized selector sent to instance 0x7fff8861bc00
2021-02-24 14:44:46.957 python[64501:5438075] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7fa4e144c820> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff8861bc00
2021-02-24 14:44:48.194 python[64501:5438075] -[NSNull length]: unrecognized selector sent to instance 0x7fff8861bc00
2021-02-24 14:44:48.194 python[64501:5438075] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7fa4e144c820> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff8861bc00
14:45:20 ERROR PluginError: Error in plugin 'napari-czifile2', hook 'napari_get_reader'
  Cause was: ValueError('cannot reshape array of size 15686422524 into shape (1,1,1,30253,86418,3)')
    in file: /Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/napari_czifile2/_reader.py
    at line: 71
     author: Jonas Windhager
      email: jonas.windhager@uzh.ch
    package: napari-czifile2
        url: https://github.com/BodenmillerGroup/napari-czifile2
    version: 0.1.1

14:45:20 ERROR PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
  Cause was: ValueError('Could not find a format to read the specified file in single-image mode')
    in file: /Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/imageio/core/functions.py
    at line: 181
     author: napari team
      email: napari-steering-council@googlegroups.com
    package: napari
        url: https://napari.org
    version: 0.4.5
```

### PR DESCRIPTION
**Pull request by jwindhager**
This pull request adds support for .czi files containing multiple regions ("scenes"). Install with:
```
pip install git+https://github.com/BodenmillerGroup/napari-czifile2.git@multiregion
```

Please carefully check whether everything works as expected. In particular, please check whether the relative positioning of the regions looks correct (e.g. by comparing with the Zeiss software). Thanks!

Closes #1

### CODE REVIEW

**Comment by nilseling** [comment]
I can now open a multi-region czi but the transformation using napping doesn't quite seem to work. I get positive coordinates after transformation from IF to .czi. The coordinates on the .czi should be negative, making them positive on the panoramas.

**Comment by jwindhager** [comment]
Did you try with napping from `master` or `centroid-transform`?

**Comment by nilseling** [comment]
That was from the `master` branch

**Comment by jwindhager** [comment]
should be fixed now

**Comment by jwindhager** [comment]
Any update here @nilseling?

**Comment by jwindhager** [comment]
Merging into master, please reopen issue #1 if problems still persist

**Pull request merged**
